src/Public/Models/ViewModels/LayoutViewModel.cs
namespace Public.Models.ViewModels;

public class LayoutViewModel
{
    /*
     * Shared views like '_Layout.cshtml' cannot use an `IViewLocalizer`, because 
     * that option only works when the file matches the route. Instead, a generic 
     * localizer such as `IStringLocalizer<>` must be used. This file provides the 
     * required type parameter for that.
     * 
     * It doesn't matter that there is nothing in this class.
     */
}

src/Public/ViewModels/LayoutViewModel.cs
namespace Public.ViewModels;

public class LayoutViewModel
{
    /*
     * Shared views like '_Layout.cshtml' cannot use an `IViewLocalizer`, because 
     * that option only works when the file matches the route. Instead, a generic 
     * localizer such as `IStringLocalizer<>` must be used. This file provides the 
     * required type parameter for that.
     * 
     * It doesn't matter that there is nothing in this class.
     */
}

src/Public/Controllers/EmbedController.cs
using Microsoft.AspNetCore.Mvc;

namespace Public.Controllers;

[Route("embed")]
public class EmbedController : Controller
{
    [HttpGet("kakao-map")]
    public IActionResult KakaoMap()
    {
        return View();
    }
}

src/Public/ViewComponents/CultureSwitcherViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Presentation.Shared.Localization.Extensions;
using Presentation.Shared.Localization.Models;

namespace Public.ViewComponents;

/// <summary>
/// Dropdown menu to select a culture.
/// </summary>
/// <remarks>
/// See Views/Shared/Components/CultureSwitcher for the associated view.
/// </remarks>
public class CultureSwitcherViewComponent : ViewComponent
{
    private readonly LocalizationOptions _localizationOptions;

    public CultureSwitcherViewComponent(IOptions<LocalizationOptions> options)
    {
        _localizationOptions = options.Value;
    }

    public IViewComponentResult Invoke()
    {
        // Supported UI cultures, same value as `RequestLocalizationOptions.SupportedUICultures`.
        var supportedCultures = _localizationOptions.SupportedCultures;

        var model = new CultureSwitcherModel
        {
            SupportedCultures = supportedCultures,
            CurrentUICulture = HttpContext.GetRequestCulture(),
        };

        return View(model);
    }
}

src/Public/Views/Shared/LocalizedStyles.en.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap">
<link rel="preconnect" href="https://rsms.me/">
<link rel="stylesheet" href="https://rsms.me/inter/inter.css">
<style>
    body {
      font-family: "Inter", sans-serif;
      font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
    }
    h1, h2, h3, h4, h5 {
        font-family: "Montserrat", sans-serif;
    }
</style>

src/Public/Views/Shared/LocalizedStyles.ko.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap">
<link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
<style>
    body {
        font-family: "Noto Sans KR", sans-serif;
    }
    h1, h2, h3, h4, h5 {
        font-family: NanumSquare, sans-serif;
    }
</style>

src/Public/Views/Shared/_Layout.cshtml
@inject IStringLocalizer<LayoutViewModel> Localizer;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@Localizer["Hyelin Fanmeeting 2025"]</title>

    <link rel="icon" href="~/favicon.ico" sizes="32x32">
    <link rel="apple-touch-icon" href="~/images/apple-touch-icon.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/main.min.css">
    <partial name="_LocalizedStyles" />
    @RenderSection("Styles", required: false)

    <script defer src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</head>
<body class="h-100">

    <header class="navbar navbar-expand fixed-top">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbar-menu" aria-expanded="false" aria-label="@Localizer["Toggle navigation"]">
                <span class="navbar-toggler-icon"></span>
            </button>

            <nav id="navbar-menu" class="collapse navbar-collapse">
                <ul class="nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" asp-fragment="top" class="nav-link">@Localizer["Home"]</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" asp-fragment="venue-info" class="nav-link">@Localizer["Venue"]</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" asp-fragment="event-info" class="nav-link">@Localizer["Event"]</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" asp-fragment="reserve-a-seat" class="nav-link">@Localizer["Reserve a Seat"]</a>
                    </li>
                </ul>
            </nav>

            <div class="">
                <vc:culture-switcher />
            </div>

        </div>
    </header>

    <main data-bs-spy="scroll" data-bs-target="#navbar-menu" data-bs-smoothScroll="true">
        @RenderBody()
    </main>

    <footer class="py-2 text-center">
        <a asp-controller="Legal" asp-action="PrivacyPolicy">@Localizer["Privacy Policy"]</a>
        &centerdot;
        <a asp-controller="Legal" asp-action="TermsOfService">@Localizer["Terms of Service"]</a>
    </footer>
</body>
</html>

src/Public/Views/Shared/_LocalizedStyles.en.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap">
<link rel="preconnect" href="https://rsms.me/">
<link rel="stylesheet" href="https://rsms.me/inter/inter.css">
<style>
    body {
      font-family: "Inter", sans-serif;
      font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
    }
    h1, h2, h3, h4, h5 {
        font-family: "Montserrat", sans-serif;
    }
</style>

src/Public/Views/Shared/_LocalizedStyles.ja.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap">
<style>
    body {
        font-family: "Noto Sans JP", sans-serif;
    }
    h1, h2, h3, h4, h5 {
        font-family: "Noto Sans JP", sans-serif;
    }
</style>

src/Public/Views/Shared/_LocalizedStyles.ko.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap">
<link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
<style>
    body {
        font-family: "Noto Sans KR", sans-serif;
    }
    h1, h2, h3, h4, h5 {
        font-family: NanumSquare, sans-serif;
    }
</style>

src/Public/Views/Shared/_LocalizedStyles.vi.cshtml
<link rel="preconnect" href="https://rsms.me/">
<link rel="stylesheet" href="https://rsms.me/inter/inter.css">
<style>
    body {
      font-family: "Inter", sans-serif;
      font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
    }
    h1, h2, h3, h4, h5 {
      font-family: "Inter", sans-serif;
      font-feature-settings: 'liga' 1, 'calt' 1; /* fix for Chrome */
    }
</style>

src/Public/Views/Shared/_LocalizedStyles.zh-Hans.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap">
<style>
    body {
        font-family: "Noto Sans CN", sans-serif;
    }
    h1, h2, h3, h4, h5 {
        font-family: "Noto Sans CN", sans-serif;
    }
</style>

src/Public/Views/Shared/_MapWidget.cshtml
<script>
	var loadMapWidget = function ($element) {
		$element.attr('src', $($element).data('src'));
	};
</script>

﻿<div class="map-widget" style="height: 450px">
	<iframe
		class="lazy-loaded"
		data-onload="loadMapWidget"
		data-priority="10"
		data-src="@Url.Action("KakaoMap", "Embed")"
	></iframe>
</div>